libs = # No default library dependencies.

# Import ICU library for Unicode configuration.
#
if $config.libcxxopts.use_unicode
  import libs += libicuuc%lib{icuuc}

# Header-Only Library
#
lib{cxxopts}: hxx{cxxopts} $libs
{
  cxx.export.poptions = "-I$src_base"
  cxx.export.libs = $libs
}

# Set macro for Unicode configuration in the header.
#
if $config.libcxxopts.use_unicode
  lib{cxxopts}: cxx.export.poptions += -DCXXOPTS_USE_UNICODE

# Installation is correctly handled by default.
#
# hxx{cxxopts}@./: install = include/
