
lib{cxxopts}: hxx{*}

out_inc = [dir_path] $out_root/include/
src_inc = [dir_path] $src_root/include/

lib{cxxopts}:
{
  cxx.poptions = "-I$out_inc" "-I$src_inc"
  cxx.export.poptions = "-I$out_inc" "-I$src_inc"
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
if $version.pre_release
  lib{cxxopts}: bin.lib.version = "-$version.project_id"
else
  lib{cxxopts}: bin.lib.version = "-$version.major.$version.minor"
