
lib{cxxopts}: hxx{*}

out_inc = [dir_path] $out_root/include/
src_inc = [dir_path] $src_root/include/

lib{cxxopts}:
{
  cxx.poptions = "-I$out_inc" "-I$src_inc"
  cxx.export.poptions = "-I$out_inc" "-I$src_inc"
}
